const careers = [
  // Frontend Developer
  {
    jobId: "ASTRAIM-EXTERNAL-141588",
    workExperience: "2-3 Years",
    jobTitle: "Frontend Developer",
    responsibilities: [
      "As part of the AstraAim Delivery team, you will work on implementing designs, developing high quality frontend components and systems, partnering with our clients to ensure high quality deliverables.",
      "You will create technical artifacts and be the first point of contact in responding to frontend production issues and conducting any technical analysis to arrive at solutions.",
      "You will share your learnings from projects through knowledge management initiatives and leverage knowledge from other projects to drive high efficiency and effectiveness.",
      "You will be a key contributor to building efficient frontend components/systems and if you think you fit right in to help our clients navigate their next in their digital transformation journey, this is the place for you!",
    ],
    technicalAndProfessionalRequirements: [
      "Primary skills: Technology->JavaScript->React.js, Angular",
    ],
    preferredSkills: ["Technology->JavaScript->React.js, Angular"],
    additionalResponsibilities: [
      "Advanced conceptual understanding of at least one frontend framework/library",
      "Advanced conceptual understanding of HTML, CSS, and JavaScript",
      "Understanding of Software Engineering with practice in at least one project",
      "Ability to contribute in medium to complex tasks independently",
      "Exposure to Design Principles and ability to understand Design Specifications independently",
      "Ability to run Test Cases and scenarios as per the plan",
      "Ability to accept and respond to production issues and coordinate with stakeholders",
      "Good understanding of SDLC",
      "Analytical abilities",
      "Logical thinking",
      "Awareness of latest frontend technologies and trends",
    ],
    educationalRequirements: "Bachelor of Engineering",
    serviceLine: "Application Development and Maintenance",
    hotJob: true,
  },
  // Backend Developer
  {
    jobId: "ASTRAIM-EXTERNAL-141589",
    workExperience: "2-3 Years",
    jobTitle: "Backend Developer",
    responsibilities: [
      "As part of the AstraAim Delivery team, you will work on implementing designs, developing high quality backend components and systems, partnering with our clients to ensure high quality deliverables.",
      "You will create technical artifacts and be the first point of contact in responding to backend production issues and conducting any technical analysis to arrive at solutions.",
      "You will share your learnings from projects through knowledge management initiatives and leverage knowledge from other projects to drive high efficiency and effectiveness.",
      "You will be a key contributor to building efficient backend components/systems and if you think you fit right in to help our clients navigate their next in their digital transformation journey, this is the place for you!",
    ],
    technicalAndProfessionalRequirements: [
      "Primary skills: Technology->Java->Spring Boot",
    ],
    preferredSkills: ["Technology->Java->Spring Boot"],
    additionalResponsibilities: [
      "Advanced conceptual understanding of at least one backend framework/library",
      "Advanced conceptual understanding of databases and server-side programming",
      "Understanding of Software Engineering with practice in at least one project",
      "Ability to contribute in medium to complex tasks independently",
      "Exposure to Design Principles and ability to understand Design Specifications independently",
      "Ability to run Test Cases and scenarios as per the plan",
      "Ability to accept and respond to production issues and coordinate with stakeholders",
      "Good understanding of SDLC",
      "Analytical abilities",
      "Logical thinking",
      "Awareness of latest backend technologies and trends",
    ],
    educationalRequirements: "Bachelor of Engineering",
    serviceLine: "Application Development and Maintenance",
    hotJob: true,
  },
  // Database Developer
  {
    jobId: "ASTRAIM-EXTERNAL-141590",
    workExperience: "2-3 Years",
    jobTitle: "Database Developer",
    responsibilities: [
      "As part of the AstraAim Delivery team, you will work on implementing designs, developing high quality database solutions, partnering with our clients to ensure high quality deliverables.",
      "You will create technical artifacts and be the first point of contact in responding to database production issues and conducting any technical analysis to arrive at solutions.",
      "You will share your learnings from projects through knowledge management initiatives and leverage knowledge from other projects to drive high efficiency and effectiveness.",
      "You will be a key contributor to building efficient database systems and if you think you fit right in to help our clients navigate their next in their digital transformation journey, this is the place for you!",
    ],
    technicalAndProfessionalRequirements: [
      "Primary skills: Technology->Database->SQL, NoSQL",
    ],
    preferredSkills: ["Technology->Database->SQL, NoSQL"],
    additionalResponsibilities: [
      "Advanced conceptual understanding of at least one database technology",
      "Advanced conceptual understanding of SQL and database optimization",
      "Understanding of Software Engineering with practice in at least one project",
      "Ability to contribute in medium to complex tasks independently",
      "Exposure to Design Principles and ability to understand Design Specifications independently",
      "Ability to run Test Cases and scenarios as per the plan",
      "Ability to accept and respond to production issues and coordinate with stakeholders",
      "Good understanding of SDLC",
      "Analytical abilities",
      "Logical thinking",
      "Awareness of latest database technologies and trends",
    ],
    educationalRequirements: "Bachelor of Engineering",
    serviceLine: "Application Development and Maintenance",
    hotJob: true,
  },
  // UI/UX Designer
  {
    jobId: "ASTRAIM-EXTERNAL-141591",
    workExperience: "2-3 Years",
    jobTitle: "UI/UX Designer",
    responsibilities: [
      "As part of the AstraAim Delivery team, you will work on implementing designs, developing high quality user interfaces and experiences, partnering with our clients to ensure high quality deliverables.",
      "You will create technical artifacts and be the first point of contact in responding to UI/UX production issues and conducting any technical analysis to arrive at solutions.",
      "You will share your learnings from projects through knowledge management initiatives and leverage knowledge from other projects to drive high efficiency and effectiveness.",
      "You will be a key contributor to building efficient user interfaces and experiences and if you think you fit right in to help our clients navigate their next in their digital transformation journey, this is the place for you!",
    ],
    technicalAndProfessionalRequirements: [
      "Primary skills: Technology->Design->Figma, Adobe XD",
    ],
    preferredSkills: ["Technology->Design->Figma, Adobe XD"],
    additionalResponsibilities: [
      "Advanced conceptual understanding of UI/UX principles",
      "Advanced conceptual understanding of design tools and prototyping",
      "Understanding of Software Engineering with practice in at least one project",
      "Ability to contribute in medium to complex tasks independently",
      "Exposure to Design Principles and ability to understand Design Specifications independently",
      "Ability to run Test Cases and scenarios as per the plan",
      "Ability to accept and respond to production issues and coordinate with stakeholders",
      "Good understanding of SDLC",
      "Analytical abilities",
      "Logical thinking",
      "Awareness of latest design technologies and trends",
    ],
    educationalRequirements: "Bachelor of Design",
    serviceLine: "Application Development and Maintenance",
    hotJob: true,
  },
  // Digital Marketing Specialist
  {
    jobId: "ASTRAIM-EXTERNAL-141592",
    workExperience: "2-3 Years",
    jobTitle: "Digital Marketing Specialist",
    responsibilities: [
      "As part of the AstraAim Delivery team, you will work on implementing digital marketing strategies, developing high quality marketing campaigns, partnering with our clients to ensure high quality deliverables.",
      "You will create technical artifacts and be the first point of contact in responding to marketing production issues and conducting any technical analysis to arrive at solutions.",
      "You will share your learnings from projects through knowledge management initiatives and leverage knowledge from other projects to drive high efficiency and effectiveness.",
      "You will be a key contributor to building efficient marketing campaigns and if you think you fit right in to help our clients navigate their next in their digital transformation journey, this is the place for you!",
    ],
    technicalAndProfessionalRequirements: [
      "Primary skills: Technology->Marketing->SEO, SEM",
    ],
    preferredSkills: ["Technology->Marketing->SEO, SEM"],
    additionalResponsibilities: [
      "Advanced conceptual understanding of digital marketing principles",
      "Advanced conceptual understanding of SEO and SEM",
      "Understanding of Software Engineering with practice in at least one project",
      "Ability to contribute in medium to complex tasks independently",
      "Exposure to Design Principles and ability to understand Design Specifications independently",
      "Ability to run Test Cases and scenarios as per the plan",
      "Ability to accept and respond to production issues and coordinate with stakeholders",
      "Good understanding of SDLC",
      "Analytical abilities",
      "Logical thinking",
      "Awareness of latest marketing technologies and trends",
    ],
    educationalRequirements: "Bachelor of Marketing",
    serviceLine: "Digital Marketing",
    hotJob: true,
  },
  // Accountant
  {
    jobId: "ASTRAIM-EXTERNAL-141593",
    workExperience: "2-3 Years",
    jobTitle: "Accountant",
    responsibilities: [
      "As part of the AstraAim Delivery team, you will work on implementing accounting processes, developing high quality financial reports and systems, partnering with our clients to ensure high quality deliverables.",
      "You will create technical artifacts and be the first point of contact in responding to accounting production issues and conducting any technical analysis to arrive at solutions.",
      "You will share your learnings from projects through knowledge management initiatives and leverage knowledge from other projects to drive high efficiency and effectiveness.",
      "You will be a key contributor to building efficient accounting systems and if you think you fit right in to help our clients navigate their next in their digital transformation journey, this is the place for you!",
    ],
    technicalAndProfessionalRequirements: [
      "Primary skills: Technology->Accounting->GAAP, IFRS",
    ],
    preferredSkills: ["Technology->Accounting->GAAP, IFRS"],
    additionalResponsibilities: [
      "Advanced conceptual understanding of accounting principles",
      "Advanced conceptual understanding of financial reporting",
      "Understanding of Software Engineering with practice in at least one project",
      "Ability to contribute in medium to complex tasks independently",
      "Exposure to Design Principles and ability to understand Design Specifications independently",
      "Ability to run Test Cases and scenarios as per the plan",
      "Ability to accept and respond to production issues and coordinate with stakeholders",
      "Good understanding of SDLC",
      "Analytical abilities",
      "Logical thinking",
      "Awareness of latest accounting technologies and trends",
    ],
    educationalRequirements: "Bachelor of Accounting",
    serviceLine: "Finance and Accounting",
    hotJob: true,
  },
];
export default careers;
